### ISSUE TITLE
ERROR Cannot prepare tests due to an error: Unexpected token export

### ISSUE THREAD

**Issue by alexyem0222** [abhinaba-ghosh/testcafe-lighthouse#4]
Hello, installed the package via npm into my repo and when trying to run a sample test via any of the test commands, there is an error:

testcafe-lighthouse/src/audit.js:18
export const testcafeLighthouseAudit = async (auditConfig = {}) => {
^^^^^^
SyntaxError: Unexpected token export

Thanks, let me know if you need more information from me

**Comment by abhinaba-ghosh** [comment]
Hi @alexyem0222 , can you provide the node version you are using?

**Comment by alexyem0222** [comment]
Hi @abhinaba-ghosh, using v10.15.3

**Comment by abhinaba-ghosh** [comment]
Hi @alexyem0222 , I am working on the same. I will get back very soon.

**Comment by abhinaba-ghosh** [comment]
Hi @alexyem0222 ,

Issue is fixed in version ```1.2.0```. But there is a fundamental change. You now need to send ```url``` as a parameter, like:

```js
import { testcafeLighthouseAudit } from 'testcafe-lighthouse';

fixture(`Audit Test`).page('https://angular.io/');

test('user audits webpage with specific thresholds', async (t) => {
  const currentURL = await t.eval(() => document.documentURI);
  console.log('url:', currentURL);

  await testcafeLighthouseAudit({
    url: currentURL,
    cdpPort: 9222,
  });
});

```

Please try the updated version and let me know if that works for you. Early feedback will be much appreciated.

**Comment by alexyem0222** [comment]
Hi @abhinaba-ghosh, this now works, thank you!

A separate question if I may, is it possible to run this on cloud web testing platforms?

For instance, using https://github.com/DevExpress/testcafe-browser-provider-browserstack?

Thanks.

**Comment by abhinaba-ghosh** [comment]
Hi @alexyem0222 , let's track the browserstack task here: https://github.com/abhinaba-ghosh/testcafe-lighthouse/issues/5

**Comment by alexyem0222** [comment]
Sounds good @abhinaba-ghosh, thanks!
