### ISSUE TITLE
Add typescript support

### ISSUE THREAD

**Issue by alexyem0222** [abhinaba-ghosh/testcafe-lighthouse#6]
Hello again, @abhinaba-ghosh 
I was wondering if TypeScript support can also be added in to the project or directions could be provided on how to run with TypeScript.

Right now, if changing test file from JS to TS and leaving everything else the same, there is an error for currentUrl:
`Argument of type '{ url: any; cdpPort: number; htmlReport: true; reportDir: string; reportName: string; }' is not assignable to parameter of type 'testCafeLighthouseConfig'.
  Object literal may only specify known properties, and 'url' does not exist in type 'testCafeLighthouseConfig'.ts(2345)
const currentURL: any`

Here is the full test file:
`import { testcafeLighthouseAudit } from 'testcafe-lighthouse';

fixture(`Audit Test`).page("http://www.google.com");

//to set thresholds, consult https://github.com/abhinaba-ghosh/testcafe-lighthouse

test("user performs lighthouse audit", async t => {
  const currentURL = await t.eval(() => document.documentURI);
  await testcafeLighthouseAudit({
    url: currentURL,
    cdpPort: 9222,
    htmlReport: true, //defaults to false
    reportDir: `results`, //defaults to `${process.cwd()}/lighthouse`
    reportName: `lighthouse-${new Date().getTime()}.html` //defaults to `lighthouse-${new Date().getTime()}.html`
  });
});`

Thanks

**Comment by abhinaba-ghosh** [comment]
Hi @alexyem0222 , thanks for pointing out. Type definitions were always present, but I missed the `url` part in the types. Please upgrade to version `1.2.1`

You may also want to add types in the `tsconfig.json` file like:

```json
{
  "compilerOptions": {
    "types": [...other types, "testcafe-lighthouse"]
  }
}
```

Let me know if this works!

**Comment by abhinaba-ghosh** [comment]
> htmlReport: true, //defaults to false
> reportDir: `results`, //defaults to `${process.cwd()}/lighthouse`
> reportName: `lighthouse-${new Date().getTime()}.html` //defaults to `lighthouse-${new Date().getTime()}.html`
> });
> });`

Do not use the `comments` in the config. It will throw error :)

**Comment by alexyem0222** [comment]
This works, thanks for the quick fix @abhinaba-ghosh!
